/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountTransactionDialog: typeof import('./src/components/asset/AccountTransactionDialog.vue')['default']
    AddAssetModal: typeof import('./src/components/asset/AddAssetModal.vue')['default']
    AssetListView: typeof import('./src/components/asset/AssetListView.vue')['default']
    AssetManager: typeof import('./src/components/mypage/AssetManager.vue')['default']
    AssetTreeTable: typeof import('./src/components/asset/AssetTreeTable.vue')['default']
    AssetTypeDataTable: typeof import('./src/components/asset/AssetTypeDataTable.vue')['default']
    AssetViewModeToggle: typeof import('./src/components/asset/AssetViewModeToggle.vue')['default']
    BacktesterControls: typeof import('./src/components/backtester/BacktesterControls.vue')['default']
    BacktesterResultDetails: typeof import('./src/components/backtester/BacktesterResultDetails.vue')['default']
    BacktesterResults: typeof import('./src/components/backtester/BacktesterResults.vue')['default']
    BacktesterSummaryTable: typeof import('./src/components/backtester/BacktesterSummaryTable.vue')['default']
    BookmarkManager: typeof import('./src/components/mypage/BookmarkManager.vue')['default']
    BrokerageUploadDialog: typeof import('./src/components/asset/BrokerageUploadDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    CalculatorLayout: typeof import('./src/components/calculators/CalculatorLayout.vue')['default']
    CalendarGrid: typeof import('./src/components/CalendarGrid.vue')['default']
    CalendarTickerSelector: typeof import('./src/components/CalendarTickerSelector.vue')['default']
    Card: typeof import('primevue/card')['default']
    ColumnGroup: typeof import('primevue/columngroup')['default']
    CompanyLogo: typeof import('./src/components/CompanyLogo.vue')['default']
    DateAndInvestment: typeof import('./src/components/backtester/controls/DateAndInvestment.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EnhancedTransactionDialog: typeof import('./src/components/asset/EnhancedTransactionDialog.vue')['default']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    FamilyMemberList: typeof import('./src/components/asset/FamilyMemberList.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FilterInput: typeof import('./src/components/FilterInput.vue')['default']
    GroupItem: typeof import('./src/components/thumbnail/GroupItem.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingOverlay: typeof import('./src/components/common/LoadingOverlay.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    PortfolioInput: typeof import('./src/components/backtester/controls/PortfolioInput.vue')['default']
    PortfolioItem: typeof import('./src/components/backtester/controls/PortfolioItem.vue')['default']
    ProfileSettings: typeof import('./src/components/mypage/ProfileSettings.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ResponsiveDialog: typeof import('./src/components/common/ResponsiveDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('primevue/row')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    StockCalculators: typeof import('./src/components/StockCalculators.vue')['default']
    StockCalculatorsUnified: typeof import('./src/components/calculators/StockCalculatorsUnified.vue')['default']
    StockChartCard: typeof import('./src/components/StockChartCard.vue')['default']
    StockHeader: typeof import('./src/components/StockHeader.vue')['default']
    StockHistoryPanel: typeof import('./src/components/StockHistoryPanel.vue')['default']
    StockHoldingsChart: typeof import('./src/components/charts/StockHoldingsChart.vue')['default']
    StockMappingDialog: typeof import('./src/components/asset/StockMappingDialog.vue')['default']
    StockPriceCandlestickChart: typeof import('./src/components/charts/StockPriceCandlestickChart.vue')['default']
    StockTimelineModal: typeof import('./src/components/StockTimelineModal.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    ThumbnailItem: typeof import('./src/components/thumbnail/ThumbnailItem.vue')['default']
    TransactionHistoryDialog: typeof import('./src/components/asset/TransactionHistoryDialog.vue')['default']
    TreeTable: typeof import('primevue/treetable')['default']
    WeekdayRotatingTag: typeof import('./src/components/WeekdayRotatingTag.vue')['default']
  }
}
