from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path

if __package__ in {None, ""}:
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.content_pipeline.content_templates import (
    ContentEvent,
    blog_cover_html,
    naver_markdown,
    social_square_html,
    toss_text,
)
from scripts.content_pipeline.database import DEFAULT_DB_PATH
from scripts.content_pipeline.models import utc_now_iso


ELIGIBLE_STATUSES = ("official", "cross_checked")


def load_event(database_path: Path, event_id: int | None, allow_review: bool) -> ContentEvent:
    statuses = (*ELIGIBLE_STATUSES, "needs_review") if allow_review else ELIGIBLE_STATUSES
    placeholders = ",".join("?" for _ in statuses)
    id_filter = "AND e.id = ?" if event_id is not None else ""
    parameters: list[object] = [*statuses]
    if event_id is not None:
        parameters.append(event_id)
    query = f"""
        SELECT e.*,
            (
                SELECT previous.distribution_per_share
                FROM distribution_events previous
                WHERE previous.ticker = e.ticker
                  AND previous.ex_date < e.ex_date
                  AND previous.verification_status IN ('official', 'cross_checked')
                ORDER BY previous.ex_date DESC
                LIMIT 1
            ) AS previous_distribution
        FROM distribution_events e
        WHERE e.verification_status IN ({placeholders}) {id_filter}
        ORDER BY e.declared_date DESC, e.id DESC
        LIMIT 1
    """
    connection = sqlite3.connect(database_path)
    connection.row_factory = sqlite3.Row
    try:
        row = connection.execute(query, parameters).fetchone()
    finally:
        connection.close()
    if row is None:
        qualifier = f"event {event_id}" if event_id is not None else "an eligible event"
        raise SystemExit(f"Could not find {qualifier}; only verified events are generated by default.")
    return ContentEvent(
        id=int(row["id"]),
        provider_slug=row["provider_slug"],
        ticker=row["ticker"],
        fund_name=row["fund_name"],
        distribution_per_share=row["distribution_per_share"],
        currency=row["currency"],
        declared_date=row["declared_date"],
        ex_date=row["ex_date"],
        payable_date=row["payable_date"],
        official_url=row["official_url"],
        verification_status=row["verification_status"],
        previous_distribution=row["previous_distribution"],
    )


def generate_bundle(event: ContentEvent, output_root: Path) -> Path:
    bundle_dir = output_root / f"{event.declared_date}-{event.ticker.lower()}-{event.id}"
    bundle_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "toss.txt": toss_text(event),
        "naver-blog.md": naver_markdown(event),
        "social-square.html": social_square_html(event),
        "blog-cover.html": blog_cover_html(event),
    }
    for name, content in files.items():
        (bundle_dir / name).write_text(content, encoding="utf-8")
    manifest = {
        "schemaVersion": 1,
        "generatedAt": utc_now_iso(),
        "eventId": event.id,
        "provider": event.provider_slug,
        "ticker": event.ticker,
        "title": f"{event.ticker} 배당 발표: 주당 ${event.amount_display}",
        "declaredDate": event.declared_date,
        "exDate": event.ex_date,
        "payableDate": event.payable_date,
        "distributionPerShare": event.distribution_per_share,
        "currency": event.currency,
        "changeLabel": event.change_label,
        "verificationStatus": event.verification_status,
        "officialUrl": event.official_url,
        "files": {
            **{name: name for name in files},
            "social-square.png": "social-square.png",
            "blog-cover.png": "blog-cover.png",
        },
    }
    (bundle_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return bundle_dir


def generate_all_bundles(database_path: Path, output_root: Path) -> list[Path]:
    """Generate once per verified ledger event; directory naming is the idempotency key."""
    connection = sqlite3.connect(database_path)
    try:
        event_ids = [row[0] for row in connection.execute(
            "SELECT id FROM distribution_events WHERE verification_status IN ('official', 'cross_checked') ORDER BY id"
        )]
    finally:
        connection.close()
    return [generate_bundle(load_event(database_path, event_id, False), output_root) for event_id in event_ids]


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a verified distribution content bundle")
    parser.add_argument("--db", type=Path, default=DEFAULT_DB_PATH)
    parser.add_argument("--event-id", type=int)
    parser.add_argument("--allow-review", action="store_true")
    parser.add_argument("--output", type=Path, default=Path("var/content-studio/generated"))
    args = parser.parse_args()
    event = load_event(args.db, args.event_id, args.allow_review)
    bundle = generate_bundle(event, args.output)
    print(bundle)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
