// stock/src/utils/chartColors.js

const colorPalettes = {
    'A': { dividend: '#F4CCCC', highlight: '#FE0000', lineDividend: '#5f5f5f', prevPrice: '#BDBDBD', currentPrice: '#FE0000', openPrice: '#FF8A80', nextPrice: '#D32F2F', dividendText: '#212121', highlightText: '#FFFFFF', prevPriceText: '#FFFFFF', currentPriceText: '#FFFFFF', openPriceText: '#212121', nextPriceText: '#FFFFFF' },
    'B': { dividend: '#FFF2CD', highlight: '#FABD03', lineDividend: '#5f5f5f', prevPrice: '#BDBDBD', currentPrice: '#FABD03', openPrice: '#FFD180', nextPrice: '#F57F17', dividendText: '#212121', highlightText: '#212121', prevPriceText: '#FFFFFF', currentPriceText: '#212121', openPriceText: '#212121', nextPriceText: '#FFFFFF' },
    'C': { dividend: '#D8EAD2', highlight: '#34A853', lineDividend: '#5f5f5f', prevPrice: '#BDBDBD', currentPrice: '#34A853', openPrice: '#B9F6CA', nextPrice: '#1B5E20', dividendText: '#212121', highlightText: '#FFFFFF', prevPriceText: '#FFFFFF', currentPriceText: '#FFFFFF', openPriceText: '#212121', nextPriceText: '#FFFFFF' },
    'D': { dividend: '#CFE2F3', highlight: '#4A86E8', lineDividend: '#5f5f5f', prevPrice: '#BDBDBD', currentPrice: '#4A86E8', openPrice: '#82B1FF', nextPrice: '#2962FF', dividendText: '#212121', highlightText: '#FFFFFF', prevPriceText: '#FFFFFF', currentPriceText: '#FFFFFF', openPriceText: '#212121', nextPriceText: '#FFFFFF' },
    '월요일': { dividend: '#E1D5E7', highlight: '#9900FF', lineDividend: '#5f5f5f', prevPrice: '#BDBDBD', currentPrice: '#9900FF', openPrice: '#EA80FC', nextPrice: '#6A1B9A', dividendText: '#212121', highlightText: '#FFFFFF', prevPriceText: '#FFFFFF', currentPriceText: '#FFFFFF', openPriceText: '#212121', nextPriceText: '#FFFFFF' },
    '화요일': { dividend: '#D0E0E3', highlight: '#00B8D4', lineDividend: '#5f5f5f', prevPrice: '#BDBDBD', currentPrice: '#00B8D4', openPrice: '#84FFFF', nextPrice: '#006064', dividendText: '#212121', highlightText: '#212121', prevPriceText: '#FFFFFF', currentPriceText: '#212121', openPriceText: '#212121', nextPriceText: '#FFFFFF' },
    '수요일': { dividend: '#C6D5F7', highlight: '#3D5AFE', lineDividend: '#5f5f5f', prevPrice: '#BDBDBD', currentPrice: '#3D5AFE', openPrice: '#8C9EFF', nextPrice: '#304FFE', dividendText: '#212121', highlightText: '#FFFFFF', prevPriceText: '#FFFFFF', currentPriceText: '#FFFFFF', openPriceText: '#212121', nextPriceText: '#FFFFFF' },
    '목요일': { dividend: '#FFE0B2', highlight: '#FF6D00', lineDividend: '#bbbbbb', prevPrice: '#BDBDBD', currentPrice: '#FF6D00', openPrice: '#FFAB40', nextPrice: '#E65100', dividendText: '#212121', highlightText: '#FFFFFF', prevPriceText: '#FFFFFF', currentPriceText: '#FFFFFF', openPriceText: '#212121', nextPriceText: '#FFFFFF' },
    '금요일': { dividend: '#F8BBD0', highlight: '#E91E63', lineDividend: '#5f5f5f', prevPrice: '#BDBDBD', currentPrice: '#E91E63', openPrice: '#FF80AB', nextPrice: '#880E4F', dividendText: '#212121', highlightText: '#FFFFFF', prevPriceText: '#FFFFFF', currentPriceText: '#FFFFFF', openPriceText: '#212121', nextPriceText: '#FFFFFF' },
    'default': { dividend: '#757575', highlight: '#BDBDBD', lineDividend: '#5f5f5f', prevPrice: '#9E9E9E', currentPrice: '#FAFAFA', openPrice: '#E0E0E0', nextPrice: '#424242', dividendText: '#FFFFFF', highlightText: '#212121', prevPriceText: '#FFFFFF', currentPriceText: '#212121', openPriceText: '#212121', nextPriceText: '#FFFFFF' }
};

export function getChartColorsByGroup(group) {
    return colorPalettes[group] || colorPalettes['default'];
}