<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
type RenderFile = { eventId: number; ticker: string; exDate?: string; name: string; url: string };
type Bundle = { eventId: number; ticker: string; exDate: string; toss?: RenderFile; naver?: RenderFile; social?: RenderFile; socialPng?: RenderFile; cover?: RenderFile; coverPng?: RenderFile };
type Modal = { title: string; file: RenderFile; kind: 'text' | 'image' };
const renders = ref<RenderFile[]>([]); const error = ref(''); const modal = ref<Modal | null>(null); const textContent = ref(''); const copyStatus = ref('');
const bundles = computed<Bundle[]>(() => { const map = new Map<number, Bundle>(); for (const render of renders.value) { let b = map.get(render.eventId); if (!b) { b = { eventId: render.eventId, ticker: render.ticker, exDate: render.exDate || '확인 필요' }; map.set(render.eventId, b); } if (render.name === 'toss.txt') b.toss = render; if (render.name === 'naver-blog.md') b.naver = render; if (render.name === 'social-square.html') b.social = render; if (render.name === 'social-square.png') b.socialPng = render; if (render.name === 'blog-cover.html') b.cover = render; if (render.name === 'blog-cover.png') b.coverPng = render; } return [...map.values()].sort((a, b) => b.eventId - a.eventId); });
async function load() { error.value = ''; try { const response = await fetch('/content-studio/renders.json', { cache: 'no-store' }); if (!response.ok) throw new Error(`산출물 목록을 읽지 못했습니다 (${response.status})`); const payload = await response.json(); renders.value = Array.isArray(payload.renders) ? payload.renders.filter((x: Partial<RenderFile>) => typeof x.url === 'string' && typeof x.name === 'string' && typeof x.ticker === 'string') : []; } catch (e) { error.value = e instanceof Error ? e.message : '산출물 목록을 불러오지 못했습니다.'; } }
async function openText(title: string, file?: RenderFile) { if (!file) return; copyStatus.value = ''; textContent.value = '불러오는 중…'; modal.value = { title, file, kind: 'text' }; try { textContent.value = await (await fetch(file.url, { cache: 'no-store' })).text(); } catch { textContent.value = '내용을 불러오지 못했습니다.'; } }
function openImage(title: string, file?: RenderFile) { if (file) { copyStatus.value = ''; modal.value = { title, file, kind: 'image' }; } }
function pngFor(file: RenderFile) { const b = bundles.value.find((x) => x.eventId === file.eventId); return file.name === 'social-square.html' ? b?.socialPng : b?.coverPng; }
function downloadName(file: RenderFile) { const ticker = file.ticker.replace(/[^a-zA-Z0-9._-]/g, '_'); const exDate = (file.exDate || 'date-unconfirmed').replace(/[^0-9-]/g, ''); return `${ticker}-${exDate}-${file.name === 'social-square.png' ? 'square' : 'cover'}.png`; }
async function copyText() { try { await navigator.clipboard.writeText(textContent.value); copyStatus.value = '복사했습니다.'; } catch { copyStatus.value = '복사 권한을 허용한 뒤 다시 시도하세요.'; } }
onMounted(load);
</script>
<template>
<section class="view"><header><div><p>CONTENT STUDIO ADMIN</p><h1>산출물</h1></div><button type="button" @click="load">새로고침</button></header><p v-if="error" class="notice">{{ error }}</p><p v-else-if="!bundles.length" class="notice">다운로드 가능한 산출물이 없습니다.</p><div v-else class="table-wrap"><table><thead><tr><th>티커</th><th>배당락일</th><th>토스</th><th>네이버</th><th>썸네일</th><th>블로그 커버</th></tr></thead><tbody><tr v-for="bundle in bundles" :key="bundle.eventId"><td><strong>{{ bundle.ticker }}</strong></td><td>{{ bundle.exDate }}</td><td><button type="button" class="text-button" :aria-label="`${bundle.ticker} 토스 원고 열기`" :disabled="!bundle.toss" @click="openText(`${bundle.ticker} 토스`, bundle.toss)">열기</button></td><td><button type="button" class="text-button" :aria-label="`${bundle.ticker} 네이버 원고 열기`" :disabled="!bundle.naver" @click="openText(`${bundle.ticker} 네이버`, bundle.naver)">열기</button></td><td><button type="button" class="text-button" :aria-label="`${bundle.ticker} 썸네일 미리보기`" :disabled="!bundle.social" @click="openImage(`${bundle.ticker} 썸네일`, bundle.social)">미리보기</button></td><td><button type="button" class="text-button" :aria-label="`${bundle.ticker} 블로그 커버 미리보기`" :disabled="!bundle.cover" @click="openImage(`${bundle.ticker} 블로그 커버`, bundle.cover)">미리보기</button></td></tr></tbody></table></div></section><Teleport to="body"><div v-if="modal" class="backdrop" role="presentation" @click.self="modal = null"><section class="modal" role="dialog" aria-modal="true" :aria-label="modal.title"><header><h2>{{ modal.title }}</h2><button type="button" aria-label="닫기" @click="modal = null">×</button></header><template v-if="modal.kind === 'text'"><pre>{{ textContent }}</pre><footer><span>{{ copyStatus }}</span><button type="button" @click="copyText">텍스트 카피</button></footer></template><template v-else><iframe :src="modal.file.url" :title="modal.title"/><footer><span>PNG 파일을 다운로드할 수 있습니다.</span><a v-if="pngFor(modal.file)" :href="pngFor(modal.file)?.url" :download="downloadName(pngFor(modal.file)!)">PNG 다운로드</a><span v-else>PNG 생성 대기</span></footer></template></section></div></Teleport>
</template>
<style scoped>
.view{display:grid;gap:1rem}header{display:flex;align-items:end;justify-content:space-between;gap:1rem}header p{margin:0 0 .35rem;color:var(--studio-accent);font-size:.75rem;font-weight:800;letter-spacing:.1em}h1,h2{margin:0}button,.text-button{border:1px solid var(--studio-border);border-radius:.5rem;background:var(--studio-surface);color:inherit;padding:.5rem .75rem;cursor:pointer}.text-button{color:var(--studio-accent);font-weight:700}.text-button:disabled{color:var(--studio-muted);cursor:not-allowed}.notice{margin:0;padding:1rem;border:1px solid var(--studio-border);border-radius:.75rem;background:var(--studio-surface);color:var(--studio-muted)}.table-wrap{overflow:auto;border:1px solid var(--studio-border);border-radius:.75rem;background:var(--studio-surface)}table{width:100%;border-collapse:collapse}th,td{padding:.8rem;border-bottom:1px solid var(--studio-border);text-align:left;white-space:nowrap}th{color:var(--studio-muted);font-size:.75rem}.backdrop{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:1rem;background:rgb(9 17 31 / .65)}.modal{display:grid;grid-template-rows:auto minmax(0,1fr) auto;gap:1rem;width:min(760px,100%);max-height:calc(100vh - 2rem);min-width:0;padding:1.25rem;overflow:hidden;border-radius:1rem;background:var(--studio-surface);box-shadow:0 20px 60px rgb(0 0 0 / .35)}.modal header{align-items:center}.modal pre{min-width:0;min-height:0;margin:0;padding:1rem;overflow:auto;border-radius:.75rem;background:var(--studio-surface-subtle);font-size:.88rem;line-height:1.45;white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-all}.modal iframe{width:100%;height:min(68vh,630px);border:1px solid var(--studio-border);border-radius:.75rem;background:#fff}.modal footer{display:flex;align-items:center;justify-content:space-between;gap:1rem;color:var(--studio-muted)}.modal footer button,.modal footer a{color:var(--studio-accent);font-weight:800;text-decoration:none}
</style>
