# .github/workflows/update_dividends.yml

name: Update Dividend Data

on:
  schedule:
    # 한국 시간 기준 (UTC+9)
    # 매일 오전 6시 (UTC 21:00)
    - cron: "0 21 * * *"
    # 매일 오후 11시 30분 (UTC 14:30)
    - cron: "30 14 * * *"
  workflow_dispatch:

permissions:
  contents: write # 리포지토리에 커밋할 수 있도록 권한 부여

jobs:
  update-data:
    runs-on: ubuntu-22.04

    steps:
      # 1. 리포지토리 코드 가져오기
      - name: Checkout main branch
        uses: actions/checkout@v4

      # 2. 파이썬 설정 및 의존성 설치
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install requests beautifulsoup4 ... # 필요한 라이브러리 설치

      # 3. 배당금 스크레이퍼 실행
      - name: Run Dividend Scraper
        run: python scripts/scraper_dividend.py

      # 4. 변경된 파일이 있으면 자동으로 커밋
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): Update dividend data"
          # 작업 디렉토리가 아닌, 리포지토리 루트 기준의 파일 경로를 명시합니다.
          file_pattern: "stock/public/data/*.json"
          # 'main' 브랜치에 푸시하도록 명시합니다.
          branch: main
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
