name: Update Dividend Data (Twice a day)

on:
  schedule:
    - cron: '0 21 * * *'  # UTC 21:00 (한국 오전 6시)
    - cron: '30 14 * * *' # UTC 14:30 (한국 저녁 11시 30분)
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-dividends:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        
        run: pip install -r requirements.txt # requirements.txt를 사용하거나,
        

      - name: Run Dividend Scraper
        
        run: python scripts/scraper_dividend.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 변경사항이 없으면 아무것도 하지 않고 종료
          if git diff --quiet public/data/; then
            echo "No changes in dividend data to commit."
            exit 0
          fi
          
          # 변경사항이 있을 경우
          git add public/data/
          # 원격 저장소의 최신 상태를 가져옴
          git fetch origin
          # 현재 브랜치를 원격 브랜치 상태로 강제 리셋 (충돌 방지)
          git reset --hard origin/main
          
          # 다시 변경사항을 적용하고 커밋
          git add public/data/
          git commit -m "Update Dividend data [skip ci]"
          
          # 푸시
          git push